# This rule is not used by the project everest-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to enginefeatures.everest.percona.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: everest-operator
    app.kubernetes.io/managed-by: kustomize
  name: enginefeatures.everest-splithorizondnsconfig-viewer-role
rules:
- apiGroups:
  - enginefeatures.everest.percona.com
  resources:
  - splithorizondnsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - enginefeatures.everest.percona.com
  resources:
  - splithorizondnsconfigs/status
  verbs:
  - get
