# This rule is not used by the project everest-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the enginefeatures.everest.percona.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: everest-operator
    app.kubernetes.io/managed-by: kustomize
  name: enginefeatures.everest-splithorizondnsconfig-editor-role
rules:
- apiGroups:
  - enginefeatures.everest.percona.com
  resources:
  - splithorizondnsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enginefeatures.everest.percona.com
  resources:
  - splithorizondnsconfigs/status
  verbs:
  - get
