apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: dbaas-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DatabaseClusterRestore is the Schema for the databaseclusterrestores
        API.
      displayName: Database Cluster Restore
      kind: DatabaseClusterRestore
      name: databaseclusterrestores.dbaas.percona.com
      version: v1
    - description: DatabaseCluster is the Schema for the databases API.
      displayName: Database Cluster
      kind: DatabaseCluster
      name: databaseclusters.dbaas.percona.com
      version: v1
    - description: DatabaseEngine is the Schema for the databaseengines API.
      displayName: Database Engine
      kind: DatabaseEngine
      name: databaseengines.dbaas.percona.com
      version: v1
  description: Deploy database clusters easily with DBaaS operator
  displayName: DBaaS operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dbaas
  - percona
  links:
  - name: Dbaas Operator
    url: https://dbaas-operator.domain
  maintainers:
  - email: andrew.minkin@percona.com
    name: gen1us2k
  - email: denys.kondratenko@percona.com
    name: denisok
  maturity: alpha
  provider:
    name: Percona
    url: https://percona.com
  version: 0.0.0
