apiVersion: enginefeatures.everest.percona.com/v1alpha1
kind: SplitHorizonDNSConfig
metadata:
  labels:
    app.kubernetes.io/name: everest-operator
    app.kubernetes.io/managed-by: kustomize
  name: splithorizondnsconfig-sample
spec:
  # TODO(user): Add fields here
