## Append samples of your project ##
resources:
- everest_v1alpha1_databasecluster.yaml
- everest_v1alpha1_databaseengine.yaml
- everest_v1alpha1_databaseclusterrestore.yaml
- everest_v1alpha1_databaseclusterbackup.yaml
- everest_v1alpha1_backupstorage.yaml
- everest_v1alpha1_monitoringconfig.yaml
- enginefeatures.everest_v1alpha1_splithorizondnsconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
