---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: databaseengines.dbaas.percona.com
spec:
  group: dbaas.percona.com
  names:
    kind: DatabaseEngine
    listKind: DatabaseEngineList
    plural: databaseengines
    shortNames:
    - dbengine
    singular: databaseengine
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: Type
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    - jsonPath: .status.version
      name: Version
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: DatabaseEngine is the Schema for the databaseengines API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DatabaseEngineSpec is a spec for a database engine.
            properties:
              allowedVersions:
                items:
                  type: string
                type: array
              type:
                description: EngineType stands for the supported database engines.
                  Right now it's only pxc and psmdb. However, it can be ps, pg and
                  any other source.
                type: string
            required:
            - type
            type: object
          status:
            description: DatabaseEngineStatus defines the observed state of DatabaseEngine.
            properties:
              availableVersions:
                description: Versions struct represents available versions of database
                  engine components.
                properties:
                  backup:
                    additionalProperties:
                      description: Component contains information of the database
                        engine component. Database Engine component can be database
                        engine, database proxy or tools image path.
                      properties:
                        critical:
                          type: boolean
                        imageHash:
                          type: string
                        imagePath:
                          type: string
                        status:
                          type: string
                      type: object
                    type: object
                  engine:
                    additionalProperties:
                      description: Component contains information of the database
                        engine component. Database Engine component can be database
                        engine, database proxy or tools image path.
                      properties:
                        critical:
                          type: boolean
                        imageHash:
                          type: string
                        imagePath:
                          type: string
                        status:
                          type: string
                      type: object
                    type: object
                  proxy:
                    additionalProperties:
                      additionalProperties:
                        description: Component contains information of the database
                          engine component. Database Engine component can be database
                          engine, database proxy or tools image path.
                        properties:
                          critical:
                            type: boolean
                          imageHash:
                            type: string
                          imagePath:
                            type: string
                          status:
                            type: string
                        type: object
                      type: object
                    type: object
                  tools:
                    additionalProperties:
                      additionalProperties:
                        description: Component contains information of the database
                          engine component. Database Engine component can be database
                          engine, database proxy or tools image path.
                        properties:
                          critical:
                            type: boolean
                          imageHash:
                            type: string
                          imagePath:
                            type: string
                          status:
                            type: string
                        type: object
                      type: object
                    type: object
                type: object
              operatorVersion:
                type: string
              status:
                description: EngineState represents state of engine in a k8s cluster.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
